ALTER TABLE public.institutions ADD COLUMN IF NOT EXISTS website TEXT;

UPDATE public.institutions SET website = 'https://algomau.ca' WHERE name = 'Algoma University';
UPDATE public.institutions SET website = 'https://brocku.ca' WHERE name = 'Brock University';
UPDATE public.institutions SET website = 'https://carleton.ca' WHERE name = 'Carleton University';
UPDATE public.institutions SET website = 'https://www.uoguelph.ca' WHERE name = 'University of Guelph';
UPDATE public.institutions SET website = 'https://uhearst.ca' WHERE name = 'Université de Hearst';
UPDATE public.institutions SET website = 'https://www.lakeheadu.ca' WHERE name = 'Lakehead University';
UPDATE public.institutions SET website = 'https://laurentian.ca' WHERE name = 'Laurentian University';
UPDATE public.institutions SET website = 'https://www.mcmaster.ca' WHERE name = 'McMaster University';
UPDATE public.institutions SET website = 'https://www.nipissingu.ca' WHERE name = 'Nipissing University';
UPDATE public.institutions SET website = 'https://www.ocadu.ca' WHERE name = 'OCAD University';
UPDATE public.institutions SET website = 'https://www.uontario.ca' WHERE name = 'Université de l''Ontario français';
UPDATE public.institutions SET website = 'https://ontariotechu.ca' WHERE name = 'Ontario Tech University';
UPDATE public.institutions SET website = 'https://www.uottawa.ca' WHERE name = 'Université d''Ottawa University of Ottawa';
UPDATE public.institutions SET website = 'https://www.queensu.ca' WHERE name = 'Queen''s University';
UPDATE public.institutions SET website = 'https://www.rmc-cmr.ca' WHERE name = 'Royal Military College of Canada';
UPDATE public.institutions SET website = 'https://www.utoronto.ca' WHERE name = 'University of Toronto';
UPDATE public.institutions SET website = 'https://www.torontomu.ca' WHERE name = 'Toronto Metropolitan University';
UPDATE public.institutions SET website = 'https://www.trentu.ca' WHERE name = 'Trent University';
UPDATE public.institutions SET website = 'https://uwaterloo.ca' WHERE name = 'University of Waterloo';
UPDATE public.institutions SET website = 'https://www.uwo.ca' WHERE name = 'Western University';
UPDATE public.institutions SET website = 'https://www.wlu.ca' WHERE name = 'Wilfrid Laurier University';
UPDATE public.institutions SET website = 'https://www.uwindsor.ca' WHERE name = 'University of Windsor';
UPDATE public.institutions SET website = 'https://www.yorku.ca' WHERE name = 'York University';
UPDATE public.institutions SET website = 'https://www.centennialcollege.ca' WHERE name = 'Centennial College';
UPDATE public.institutions SET website = 'https://www.conestogac.on.ca' WHERE name = 'Conestoga College';
UPDATE public.institutions SET website = 'https://www.confederationcollege.ca' WHERE name = 'Confederation College of Applied Arts and Technology';
UPDATE public.institutions SET website = 'https://www.durhamcollege.ca' WHERE name = 'Durham College of Applied Arts and Technology';
UPDATE public.institutions SET website = 'https://www.fanshawec.ca' WHERE name = 'Fanshawe College';
UPDATE public.institutions SET website = 'https://www.flemingcollege.ca' WHERE name = 'Fleming College';
UPDATE public.institutions SET website = 'https://www.georgebrown.ca' WHERE name = 'George Brown College';
UPDATE public.institutions SET website = 'https://www.georgiancollege.ca' WHERE name = 'Georgian College';
UPDATE public.institutions SET website = 'https://humber.ca' WHERE name = 'Humber College Institute of Technology and Advanced Learning Humber Lakeshore Campus';
UPDATE public.institutions SET website = 'https://www.collegelacite.ca' WHERE name = 'La Cité collégiale';
UPDATE public.institutions SET website = 'https://www.lambtoncollege.ca' WHERE name = 'Lambton College';
UPDATE public.institutions SET website = 'https://www.loyalistcollege.com' WHERE name = 'Loyalist College of Applied Arts and Technology';
UPDATE public.institutions SET website = 'https://www.michener.ca' WHERE name = 'The Michener Institute for Applied Health Sciences';
UPDATE public.institutions SET website = 'https://www.mohawkcollege.ca' WHERE name = 'Mohawk College of Applied Arts and Technology';
UPDATE public.institutions SET website = 'https://www.niagaracollege.ca' WHERE name = 'Niagara College Canada';
UPDATE public.institutions SET website = 'https://www.northernc.on.ca' WHERE name = 'Northern College';
UPDATE public.institutions SET website = 'https://www.saultcollege.ca' WHERE name = 'Sault College';
UPDATE public.institutions SET website = 'https://www.senecapolytechnic.ca' WHERE name = 'Seneca College of Applied Arts and Technology';
UPDATE public.institutions SET website = 'https://www.stclaircollege.ca' WHERE name = 'St Clair College';
UPDATE public.institutions SET website = 'https://www.stlawrencecollege.ca' WHERE name = 'St Lawrence College';
UPDATE public.institutions SET website = 'https://www.cambriancollege.ca' WHERE name = 'Cambrian College of Applied Arts and Technology';
UPDATE public.institutions SET website = 'https://www.canadorecollege.ca' WHERE name = 'Canadore College of Applied Arts and Technology College Drive Campus North Bay ON';
UPDATE public.institutions SET website = 'https://www.collegeboreal.ca' WHERE name = 'Collège Boréal';
UPDATE public.institutions SET website = 'https://www.sheridancollege.ca' WHERE name = 'The Sheridan College Institute of Technology and Advanced Learning';
UPDATE public.institutions SET website = 'https://www.bcit.ca' WHERE name = 'British Columbia Institute of Technology';
UPDATE public.institutions SET website = 'https://camosun.ca' WHERE name = 'Camosun College';
UPDATE public.institutions SET website = 'https://www.capilanou.ca' WHERE name = 'Capilano University';
UPDATE public.institutions SET website = 'https://www.coastmountaincollege.ca' WHERE name = 'Coast Mountain College';
UPDATE public.institutions SET website = 'https://cnc.bc.ca' WHERE name = 'College of New Caledonia';
UPDATE public.institutions SET website = 'https://www.cotr.bc.ca' WHERE name = 'College of the Rockies';
UPDATE public.institutions SET website = 'https://www.douglascollege.ca' WHERE name = 'Douglas College';
UPDATE public.institutions SET website = 'https://www.ecuad.ca' WHERE name = 'Emily Carr University of Art and Design';
UPDATE public.institutions SET website = 'https://www.jibc.ca' WHERE name = 'Justice Institute of British Columbia';
UPDATE public.institutions SET website = 'https://www.kpu.ca' WHERE name = 'Kwantlen Polytechnic University';
UPDATE public.institutions SET website = 'https://langara.ca' WHERE name = 'Langara College';
UPDATE public.institutions SET website = 'https://www.nvit.ca' WHERE name = 'Nicola Valley Institute of Technology';
UPDATE public.institutions SET website = 'https://www.nic.bc.ca' WHERE name = 'North Island College';
UPDATE public.institutions SET website = 'https://www.nlc.bc.ca' WHERE name = 'Northern Lights College';
UPDATE public.institutions SET website = 'https://www.okanagan.bc.ca' WHERE name = 'Okanagan College';
UPDATE public.institutions SET website = 'https://www.royalroads.ca' WHERE name = 'Royal Roads University';
UPDATE public.institutions SET website = 'https://selkirk.ca' WHERE name = 'Selkirk College';
UPDATE public.institutions SET website = 'https://www.sfu.ca' WHERE name = 'Simon Fraser University';
UPDATE public.institutions SET website = 'https://www.tru.ca' WHERE name = 'Thompson Rivers University';
UPDATE public.institutions SET website = 'https://www.ubc.ca' WHERE name = 'University of British Columbia';
UPDATE public.institutions SET website = 'https://www.unbc.ca' WHERE name = 'University of Northern British columbia';
UPDATE public.institutions SET website = 'https://www.uvic.ca' WHERE name = 'University of Victoria';
UPDATE public.institutions SET website = 'https://www.ufv.ca' WHERE name = 'University of the Fraser Valley';
UPDATE public.institutions SET website = 'https://www.vcc.ca' WHERE name = 'Vancouver Community College';
UPDATE public.institutions SET website = 'https://www.viu.ca' WHERE name = 'Vancouver Island University';
UPDATE public.institutions SET website = 'https://thecdm.ca' WHERE name = 'Centre for Digital Media formerly Great Northern Way Campus';