ALTER TABLE public.institutions ADD COLUMN IF NOT EXISTS city TEXT;

UPDATE institutions SET city = 'Sault Ste. Marie' WHERE name = 'Algoma University';
UPDATE institutions SET city = 'St. Catharines' WHERE name = 'Brock University';
UPDATE institutions SET city = 'Ottawa' WHERE name = 'Carleton University';
UPDATE institutions SET city = 'Guelph' WHERE name = 'University of Guelph';
UPDATE institutions SET city = 'Hearst' WHERE name = 'Université de Hearst';
UPDATE institutions SET city = 'Thunder Bay' WHERE name = 'Lakehead University';
UPDATE institutions SET city = 'Sudbury' WHERE name = 'Laurentian University';
UPDATE institutions SET city = 'Hamilton' WHERE name = 'McMaster University';
UPDATE institutions SET city = 'North Bay' WHERE name = 'Nipissing University';
UPDATE institutions SET city = 'Toronto' WHERE name = 'OCAD University';
UPDATE institutions SET city = 'Toronto' WHERE name = 'Université de l''Ontario français';
UPDATE institutions SET city = 'Oshawa' WHERE name = 'Ontario Tech University';
UPDATE institutions SET city = 'Ottawa' WHERE name = 'Université d''Ottawa University of Ottawa';
UPDATE institutions SET city = 'Kingston' WHERE name = 'Queen''s University';
UPDATE institutions SET city = 'Toronto' WHERE name = 'University of Toronto';
UPDATE institutions SET city = 'Toronto' WHERE name = 'Toronto Metropolitan University';
UPDATE institutions SET city = 'Peterborough' WHERE name = 'Trent University';
UPDATE institutions SET city = 'Waterloo' WHERE name = 'University of Waterloo';
UPDATE institutions SET city = 'London' WHERE name = 'Western University';
UPDATE institutions SET city = 'Waterloo' WHERE name = 'Wilfrid Laurier University';
UPDATE institutions SET city = 'Windsor' WHERE name = 'University of Windsor';
UPDATE institutions SET city = 'Toronto' WHERE name = 'York University';
UPDATE institutions SET city = 'Toronto' WHERE name = 'Centennial College';
UPDATE institutions SET city = 'Kitchener' WHERE name = 'Conestoga College';
UPDATE institutions SET city = 'Thunder Bay' WHERE name = 'Confederation College of Applied Arts and Technology';
UPDATE institutions SET city = 'Oshawa' WHERE name = 'Durham College of Applied Arts and Technology';
UPDATE institutions SET city = 'London' WHERE name = 'Fanshawe College';
UPDATE institutions SET city = 'Peterborough' WHERE name = 'Fleming College';
UPDATE institutions SET city = 'Toronto' WHERE name = 'George Brown College';
UPDATE institutions SET city = 'Barrie' WHERE name = 'Georgian College';
UPDATE institutions SET city = 'Toronto' WHERE name = 'Humber College Institute of Technology and Advanced Learning Humber Lakeshore Campus';
UPDATE institutions SET city = 'Ottawa' WHERE name = 'La Cité collégiale';
UPDATE institutions SET city = 'Sarnia' WHERE name = 'Lambton College';
UPDATE institutions SET city = 'Belleville' WHERE name = 'Loyalist College of Applied Arts and Technology';
UPDATE institutions SET city = 'Toronto' WHERE name = 'The Michener Institute for Applied Health Sciences';
UPDATE institutions SET city = 'Hamilton' WHERE name = 'Mohawk College of Applied Arts and Technology';
UPDATE institutions SET city = 'Welland' WHERE name = 'Niagara College Canada';
UPDATE institutions SET city = 'Timmins' WHERE name = 'Northern College';
UPDATE institutions SET city = 'Sault Ste. Marie' WHERE name = 'Sault College';
UPDATE institutions SET city = 'Toronto' WHERE name = 'Seneca College of Applied Arts and Technology';
UPDATE institutions SET city = 'Windsor' WHERE name = 'St Clair College';
UPDATE institutions SET city = 'Kingston' WHERE name = 'St Lawrence College';
UPDATE institutions SET city = 'Sudbury' WHERE name = 'Cambrian College of Applied Arts and Technology';
UPDATE institutions SET city = 'North Bay' WHERE name = 'Canadore College of Applied Arts and Technology College Drive Campus North Bay ON';
UPDATE institutions SET city = 'Sudbury' WHERE name = 'Collège Boréal';
UPDATE institutions SET city = 'Oakville' WHERE name = 'The Sheridan College Institute of Technology and Advanced Learning';
UPDATE institutions SET city = 'Ottawa' WHERE name = 'The Algonquin College of Applied Learning and Technology';